dbcollege/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^events/', include('photologue.urls', namespace='photologue')),
    url(r'', include("website.urls", namespace="website")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^departments/(?P<deptid>\d+)/(?P<deptname>.+)/$', views.departmentPage, name="department"),
    url(r'^departments/', views.departmentIndex, name="departments-index"),
    url(r'^library/$', views.libraryIndex, name="library-index"),
    url(r'^student-union/$', views.studentUnion, name="student-union"),
    url(r'^governing-body/$', views.governingBody, name="governing-body"),
    url(r'^admin-staff/$', views.adminStaff, name="admin-staff"),    
]

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

class GoverningBodyMember(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="gb-members")
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class StaffMember(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="gb-members")
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class StudentUnionMember(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=150)
    picture = models.FileField(max_length=150, upload_to="gb-members")
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Department(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=200)
    image = models.FileField(max_length=200, upload_to="departments")
    description = RichTextUploadingField(blank=True ,null=True)
    side1desc = RichTextUploadingField(blank=True ,null=True)
    side2desc = RichTextUploadingField(blank=True ,null=True)

    def __str__(self):
        return self.name

class LibraryStaff(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=200)
    image = models.FileField(max_length=200, upload_to="library/staff")
    title = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class LibraryNewArrivals(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=200)
    image = models.FileField(max_length=200, upload_to="library/books")
    author = models.CharField(max_length=150)

    def __str__(self):
        return self.name

website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import GoverningBodyMember, StaffMember, StudentUnionMember, Department, LibraryNewArrivals, LibraryStaff

def index(request):
    gbmembers = GoverningBodyMember.objects.all()
    staffmembers = StaffMember.objects.all()

    return render(request, "index.html", {
    "gb":gbmembers, "staff":staffmembers,
    })

def contact(request):
    return render(request, "contact.html", {})

def departmentIndex(request):
    departments = Department.objects.all()

    return render(request, "departments.html", {
    "departments":departments,
    })

def departmentPage(request, deptid, deptname):
    department = Department.objects.get(id=deptid)

    return render(request, "department-page.html", {
    "dept":department,
    })

def libraryIndex(request):
    new_arrivals = LibraryNewArrivals.objects.all()
    staff = LibraryStaff.objects.all()

    return render(request, "library.html", {
    "newarrivals":new_arrivals, "staff":staff,
    })

def studentUnion(request):
    members = StudentUnionMember.objects.all()

    return render(request, "student-union.html", {
    "members":members,
    })

def adminStaff(request):
    members = StaffMember.objects.all()

    return render(request, "admin-staff.html", {
    "members":members,
    })

def governingBody(request):
    members = GoverningBodyMember.objects.all()

    return render(request, "governing-body.html", {
    "members":members,
    })

templates/accounts-staff.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Departments
{% endblock title %}

{% block content %}
<!-- Banner Starts -->
<!-- InstanceBeginEditable name="EditRegion4" -->
<div class="inside-banner" style="background-image:url(images/banner-students.jpg);">
  <div class="grid-1200">
    Departments
  </div>
</div>
<!-- InstanceEndEditable -->
<!-- Banner Ends-->

<!-- Content Area  Starts -->
<div class="grid-1200">
  <!-- InstanceBeginEditable name="main" -->
  <h2>Accounts Staff</h2>

  {% for each in members %}
  <div class="subject-box">
    <a href="#">
      <img src="{{each.picture.url}}" />
      <span>{{each.name}}</span>
      <span>{{each.title}}
    </a>
  </div>
  {% endfor %}

  <!-- InstanceEndEditable -->
</div>

<!-- Content Area  Ends -->

{% endblock content %}

templates/admin-staff.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Departments
{% endblock title %}

{% block content %}
<!-- Banner Starts -->
<!-- InstanceBeginEditable name="EditRegion4" -->
<div class="inside-banner" style="background-image:url(../static/images/banner-students.jpg);">
  <div class="grid-1200">
    Departments
  </div>
</div>
<!-- InstanceEndEditable -->
<!-- Banner Ends-->

<!-- Content Area  Starts -->
<div class="grid-1200">
  <!-- InstanceBeginEditable name="main" -->
  <h2>Adminsistration Staff</h2>

  {% for each in members %}
  <div class="subject-box">
    <a href="#">
      <img src="{{each.picture.url}}" />
      <span>{{each.name}}</span>
      <span>{{each.title}}
    </a>
  </div>
  {% endfor %}

  <!-- InstanceEndEditable -->
</div>

<!-- Content Area  Ends -->

{% endblock content %}

templates/department-page.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Department of {{dept.name}}
{% endblock title %}

{% block content %}

<div class="grid-1200" style="margin-top:100px;">
  <!-- InstanceBeginEditable name="main" -->
  <h2>Department of {{dept.name}}</h2>
  <img src="{{dept.image.url}}" class="rounded-image"/>
  <p>{{dept.description|safe}}</p>
  <br />
  <div class="cream-box">
    <div class="half-left">
      {{dept.side1desc|safe}}
    </div>
    <div class="half-right">
      {{dept.side2desc|safe}}
    </div>
  </div>
  <!-- InstanceEndEditable -->
</div>

<!-- Content Area  Ends -->

{% endblock content %}

templates/departments.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Departments
{% endblock title %}

{% block content %}
<!-- Banner Starts -->
<!-- InstanceBeginEditable name="EditRegion4" -->
<div class="inside-banner" style="background-image:url(images/banner-students.jpg);">
  <div class="grid-1200">
    Departments
  </div>
</div>
<!-- InstanceEndEditable -->
<!-- Banner Ends-->

<!-- Content Area  Starts -->
<div class="grid-1200">
  <!-- InstanceBeginEditable name="main" -->
  <h2>Departments</h2>

  {% for each in departments %}
  <div class="subject-box">
    <a href="{% url "website:department" each.pk each.name|slugify %}">
      <img src="{{each.image.url}}" />
      <span>{{each.name}}</span>
    </a>
  </div>
  {% endfor %}

  <!-- InstanceEndEditable -->
</div>

<!-- Content Area  Ends -->

{% endblock content %}

templates/footer.html
{% load staticfiles %}
<div class="clear"></div>
<!-- Footer  Starts -->
<footer>
	<div class="grid-1200">
		<div class="footer-column">
			<h5>About Us</h5>
			<ul>
				<li ><a href="/pages/about/chairmans-address/">The Chairman's Address</a></li>
				<li ><a href="/pages/about/principal-desk/">From the Principal's Desk</a></li>
				<li ><a href="/pages/about/college-profile/">College Profile</a></li>
				<li ><a href="/pages/awards/">Awards</a></li>
				<li ><a href="/pages/innovation-projects/">Innovation Projects</a></li>
				<li ><a href="/governing-body/">Governing Body</a></li>
				<li ><a href="/admin-staff/">Administrative and Accounts Staff</a></li>				
			</ul>
		</div>
		<div class="footer-column">
			<h5>Admission</h5>
			<ul>
				<li ><a href="/pages/admission/information-brochure/">Information Brochure</a></li>
				<li ><a href="/pages/admission/important-dates/">Important dates</a></li>
				<li ><a href="/pages/admission/cbcs-courses/">CBCS Courses offered</a></li>
				<li ><a href="/pages/admission/general-information/">General Information</a></li>
				<li ><a href="/pages/admission/application-process/">Application Process</a></li>
				<li ><a href="/pages/admission/procedure/">Admission Procedure</a></li>
				<li ><a href="/pages/admission/sports-admission/">Sports Admission</a></li>
				<li ><a href="/pages/admission/eca-admissions/">ECA Admissions</a></li>
				<li ><a href="/pages/admission/fee-structure/">Fee Structure</a></li>
				<li ><a href="/pages/admission/cancellation-and-refund/">Admission Cancellation and Refund</a></li>
				<li ><a href="/pages/admission/cut-offs/">Cut-Offs 2016-2017</a></li>
				<li ><a href="/pages/admission/financial-assitance/">Financial Assistance</a></li>
			</ul>
		</div>
		<div class="footer-column">
			<h5>Academics</h5>
			<ul>
				<li ><a href="{% url "website:departments-index" %}">Departments</a></li>
				<li ><a href="http://www.du.ac.in/du/index.php?page=examinations" target="_blank">Examinations</a></li>
				<li ><a href="/pages/academics/distance-learning/">Distance Learning</a></li>
			</ul>
		</div>
		<div class="footer-column">
			<h5>Student Zone</h5>
			<ul>
				<li><a href="/pages/student/campus-life">Campus Life</a></li>
				<li><a href="/pages/student/time-table/">Time Table</a></li>
				<li><a href="/pages/student/internal-assesment/">Internal Assessment</a></li>
				<li><a href="/pages/student/attendance/">Attendance</a></li>
				<li><a href="/pages/student/attendance-rules/">Attendance Rules</a></li>
				<li><a href="/pages/student/results/">Results</a></li>
				<li><a href="/pages/student/prizes/">Gold Medals and Prizes</a></li>
				<li><a href="/pages/student/scholarships/">Scholarships</a></li>
				<li><a href="/student-union/">Student Union</a></li>
				<li><a href="/pages/student/dusu-elections/">DUSU Elections</a></li>
				<li><a href="/pages/student/online-fee-payment/">Online Fee Payment</a></li>
				<li><a href="/pages/student/placement-cell/">Placement Cell</a></li>
				<li><a href="/pages/student/identity-card/">Identity Card </a></li>
				<li><a href="/pages/student/student-grievance-committee/">Student Grievance Committee</a></li>
				<li><a href="/pages/student/special-category-enabling-committee/">Special Category Enabling Committee</a></li>
			</ul>
		</div>
		<div class="footer-column">
			<h5><a href="aoc.html">Add-on Courses</a></h5>
			<ul>
				<li><a href="/pages/aoc/dot-net/">.NET</a></li>
				<li><a href="/pages/aoc/sme/">SME</a></li>
				<li><a href="/pages/aoc/smo/">SMO</a></li>
				<li><a href="/pages/aoc/para-legal">Paralegal</a></li>
				<li><a href="/pages/aoc/tally/">Tally</a></li>
				<li><a href="/pages/aoc/jyotish/">Jyotish and Vastu Shastra</a></li>
			</ul>
		</div>
		<div class="footer-column">
			<h5>More</h5>
			<ul>
				<li ><a href="http://www.du.ac.in/du/index.php?page=academic-calender" target="_blank">Academic calendar</a></li>
				<li><a href="{% static "prospectus2016.pdf" %}">Prospectus 2016</a></li>
				<li ><a href="http://www.du.ac.in/du/uploads/Guidelines/29122015_Holidays2016.pdf" target="_blank">List of holidays 2016-2017</a></li>
				<li ><a href="/pages/appointments/">Appointments/Vacancies</a></li>
				<li ><a href="/pages/rti/">RTI</a></li>
				<li ><a href="/pages/college-roster/">College Roster</a></li>
				<li ><a href="/pages/facilities/">Facilities</a></li>
				<li ><a href="/pages/reservation-cell/">SC/ST/OBC Cell</a></li>
				<li ><a href="/pages/tenders/">Tenders/Quotations </a></li>
				<li ><a href="/pages/rules-of-discipline/">Rules of Discipline</a></li>
				<li ><a href="/pages/anti-smoking-campaign">Anti-Smoking Campaign</a></li>
				<li ><a href="/pages/some-freee-zone/">Smoke Free Zone</a></li>
				<li ><a href="/pages/prevention-of-sexual-harrasment/">Prevention of Sexual Harassment</a></li>
				<li ><a href="/pages/college-committees/">College Committees</a></li>
				<li ><a href="/pages/cas2010/">CAS-2010</a></li>
				<li><a href="{% static "naac.pdf" %}">NAAC Self Study Report</a></li>
				<li><a href="{% static "annual-report.pdf" %}">Annual Report</a></li>
		</div>
	</div>
</footer>
<!-- Footer  Ends -->
<div class="copyright">
	<div class="grid-1200">
		<div class="copyright-left">
			Copyright © 2016 Deshbandhu College. All Rights Reserved.
		</div>
		<div class="designed">
			Designed, developed and managed by <a href="http://www.delhinerds.com" target="_blank">Delhi Nerds</a>
		</div>
	</div>
</div>

templates/header.html
{% load staticfiles %}
<header>
  <div class="grid-1200">

    <div class="three-lines"><img src="{% static "images/three-lines.png" %}" /></div>

    <div class="logo"><a href="{% url "website:index" %}"><img src="{% static "images/logo.png" %}" /></a></div>

    <div class="social-media">
      <a href="#"><img src="{% static "images/facebook.png" %}" /></a>
      <a href="#"><img src="{% static "images/twitter.png" %}" /></a>
      <a href="#"><img src="{% static "images/instagram.png" %}" /></a>
      <a href="#"><img src="{% static "images/linkedin.png" %}" /></a>
    </div>

    <div class="search"><input name="" type="text" class="text-searchbox" value="Search" /><input name="" type="button"  class="go" /></div>
  </div>
</header>

<div class="top-navigation" id="top-navigation">
  <div class="nav_wrapper">

    <div class="spinner-master">
      <input type="checkbox" id="spinner-form" />
      <label for="spinner-form" class="spinner-spin">
        <div class="spinner diagonal part-1"></div>
        <div class="spinner horizontal"></div>
        <div class="spinner diagonal part-2"></div>
      </label>
    </div>
    <nav id="menu" class="menu">
      <ul class="dropdown">
        <li ><a href="{% url "website:index" %}" >Home</a>

          <li ><a href="#">About Us</a>
            <ul>
              <li ><a href="/pages/about/chairmans-address/">The Chairman's Address</a></li>
              <li ><a href="/pages/about/principal-desk/">From the Principal's Desk</a></li>
              <li ><a href="/pages/about/college-profile/">College Profile</a></li>
            </ul>
          </li>

          <li ><a href="#" target="_blank" >Admission</a>
            <ul>
              <li ><a href="/pages/admission/information-brochure/">Information Brochure</a></li>
              <li ><a href="/pages/admission/important-dates/">Important dates</a></li>
              <li ><a href="/pages/admission/cbcs-courses/">CBCS Courses offered</a></li>
              <li ><a href="/pages/admission/general-information/">General Information</a></li>
              <li ><a href="/pages/admission/application-process/">Application Process</a></li>
              <li ><a href="/pages/admission/procedure/">Admission Procedure</a></li>
              <li ><a href="/pages/admission/sports-admission/">Sports Admission</a></li>
              <li ><a href="/pages/admission/eca-admissions/">ECA Admissions</a></li>
              <li ><a href="/pages/admission/fee-structure/">Fee Structure</a></li>
              <li ><a href="/pages/admission/cancellation-and-refund/">Admission Cancellation and Refund</a></li>
              <li ><a href="/pages/admission/cut-offs/">Cut-Offs 2016-2017</a></li>
              <li ><a href="/pages/admission/financial-assitance/">Financial Assistance</a></li>
            </ul>
          </li>

          <li ><a href="#"  target="_blank" >Academics</a>
            <ul>
              <li ><a href="{% url "website:departments-index" %}">Departments</a></li>
              <li ><a href="http://www.du.ac.in/du/index.php?page=examinations" target="_blank">Examinations</a></li>
              <li ><a href="/pages/academics/distance-learning/">Distance Learning</a></li>
            </ul>
          </li>

          <li ><a href="/pages/student/">Student</a>
            <ul>
              <li><a href="/pages/student/campus-life">Campus Life</a></li>
              <li><a href="/pages/student/time-table/">Time Table</a></li>
              <li><a href="/pages/student/internal-assesment/">Internal Assessment</a></li>
              <li><a href="/pages/student/attendance/">Attendance</a></li>
              <li><a href="/pages/student/attendance-rules/">Attendance Rules</a></li>
              <li><a href="/pages/student/results/">Results</a></li>
              <li><a href="/pages/student/prizes/">Gold Medals and Prizes</a></li>
              <li><a href="/pages/student/scholarships/">Scholarships</a></li>
              <li><a href="/student-union/">Student Union</a></li>
              <li><a href="/pages/student/dusu-elections/">DUSU Elections</a></li>
              <li><a href="/pages/student/online-fee-payment/">Online Fee Payment</a></li>
              <li><a href="/pages/student/placement-cell/">Placement Cell</a></li>
              <li><a href="/pages/student/identity-card/">Identity Card </a></li>
              <li><a href="/pages/student/student-grievance-committee/">Student Grievance Committee</a></li>
              <li><a href="/pages/student/special-category-enabling-committee/">Special Category Enabling Committee</a></li>
            </ul>
          </li>

          <li ><a href="{% url "website:library-index" %}">Library</a></li>

          <li ><a href="#">Alumni</a>
            <ul>
              <li ><a href="/pages/alumni/registration/">Registration</a></li>
              <li ><a href="/pages/alumni/alumni/">Alumni</a></li>
              <li ><a href="/pages/alumni/news-events/">News and Events</a></li>
              <li ><a href="/pages/alumni/search-members/">Search Members</a></li>
              <li ><a href="/pages/alumni-directory">Alumni Directory </a></li>
            </ul>
          </li>

          <li ><a href="/pages/useful-links/">Useful Links</a></li>

          <li ><a href="#">More</a>
            <ul>
              <li ><a href="http://www.du.ac.in/du/index.php?page=academic-calender" target="_blank">Academic calendar</a></li>
              <li><a href="{% static "prospectus2016.pdf" %}">Prospectus 2016</a></li>
              <li ><a href="{% static "holidays.pdf" %}" target="_blank">List of holidays 2017-2018</a></li>
              <li ><a href="/pages/appointments/">Appointments/Vacancies</a></li>
              <li ><a href="/pages/rti/">RTI</a></li>
              <li ><a href="/pages/college-roster/">College Roster</a></li>
              <li ><a href="/pages/facilities/">Facilities</a></li>
              <li ><a href="/pages/reservation-cell/">SC/ST/OBC Cell</a></li>
              <li ><a href="/pages/tenders/">Tenders/Quotations </a></li>
              <li ><a href="/pages/rules-of-discipline/">Rules of Discipline</a></li>
              <li ><a href="/pages/anti-smoking-campaign">Anti-Smoking Campaign</a></li>
              <li ><a href="/pages/some-freee-zone/">Smoke Free Zone</a></li>
              <li ><a href="/pages/prevention-of-sexual-harrasment/">Prevention of Sexual Harassment</a></li>
              <li ><a href="/pages/college-committees/">College Committees</a></li>
              <li ><a href="/pages/cas2010/">CAS-2010</a></li>
              <li><a href="{% static "naac.pdf" %}">NAAC Self Study Report</a></li>
              <li><a href="{% static "annual-report.pdf" %}">Annual Report</a></li>
            </ul>
          </li>
          <li><a href="{% url "website:contact" %}">Contact Us</a></li>
        </ul>
      </nav>
    </div>
  </div>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
Home
{% endblock title %}

{% block content %}

<!-- Banner Starts -->
<div class="container" id="slider5">
	<div class="slider">
		<div class="slider_area">
			<div class="slides">
				<div class="slide">
					<div class="banner1"><div class="banner-caption">Spirited Folk Dancers at <span>SABRANG 2016</span></div></div>
				</div>
				<div class="slide">
					<div class="banner2"><div class="banner-caption"><span>Constitution Day gathering</span> in Rapt Attention at Deshbandhu College</div></div>
				</div>
				<div class="slide">
					<div class="banner3"><div class="banner-caption" style="padding-top:150px">Hon'ble Governor of Gujarat<span>Shri Om Prakash Kohli </span>addresses the gathering at his <br />Alma Mater Deshbandhu College </div></div>
				</div>
				<div class="slide">
					<div class="banner4"><div class="banner-caption"><span>Mash-up Creativity Soars </span>at Deshbandhu College</div></div>
				</div>
			</div>
		</div>
		<div class="slider_nav"></div>
		<a class="slide_left"><img src="{% static "images/banner-arrow1.png" %}"  /></a>
		<a class="slide_right"><img src="{% static "images/banner-arrow2.png" %}"  /></a>
	</div>
</div>

<div class="grid-1200">
	<div class="half float-left" id="message-1">
		<div class="photo-box"><img src="{% static "images/principle.png" %}" />Dr. Ajay Kumar <br />Arora</div>
		<h2>From the Principal's Desk</h2>
		<p>The Deshbandhu College fraternity welcomes you and is very happy to embrace you in its fold. The south Delhi, Deshbandhu College is one of the oldest landmark institutions in the family of the colleges of the University of Delhi. </p>
		<p><a href="/pages/about/principal-desk/" class="readmore">read more</a></p>
	</div>
	<div class="half float-right" id="message-2">
		<div class="photo-box"><img src="{% static "images/chairman.png" %}" />Dr. Prakash Nanda</div>
		<h2>The Chairman’s Address</h2>
		<p>Welcome to Desh Bandhu College, a college with rich legacy, glorious past, rich present and a promising future. Education is the most powerful weapon which you can use to change the world; it not only is...</p>
		<p><a href="/pages/about/chairmans-address/" class="readmore">read more</a></p>
	</div>
</div>

<div class="cream-bg">
	<div class="grid-1200">
		<div class="twenty-five-percent">
			<h3>Student Zone</h3>
			<a href="/page/student/"><img src="{% static "images/home-pic1.png" %}"  /></a>
			<p>A peep into student activities at Deshbandhu </p>
			<a href="/pages/student/" class="readmore">read more</a>
		</div>
		<div class="twenty-five-percent">
			<h3>Digital Library</h3>
			<a href="#"><img src="{% static "images/home-pic2.png" %}"  /></a>
			<p>The world of knowledge</p>
			<a href="{% url "website:library-index" %}" class="readmore">read more</a>
		</div>
		<div class="twenty-five-percent">
			<h3>Notice Board</h3>
			<a href="/pages/notice-board/"><img src="{% static "images/home-pic3.png" %}"  /></a>
			<p>To be abreast with the latest</p>
			<a href="/pages/notice-board/" class="readmore">read more</a>
		</div>
		<div class="twenty-five-percent no-margin">
			<h3>Events</h3>
			<a href="/events/"><img src="{% static "images/home-pic4.png" %}"  /></a>
			<p>About happenings in college</p>
			<a href="/events/" class="readmore">read more</a>
		</div>
	</div>
</div>
<div class="grid-1200">
	<div class="home-left-panel">
		<h2>Photo Gallery</h2>
		<div id="slider1" class="sliderwrapper">
			<div class="contentdiv"><img src="{% static "images/photo1.jpg" %}"  /></div>
			<div class="contentdiv"><img src="{% static "images/photo2.jpg" %}"  /></div>
			<div class="contentdiv"><img src="{% static "images/photo3.jpg" %}"  /></div>
			<div class="contentdiv"><img src="{% static "images/photo4.jpg" %}"  /></div>
			<div class="contentdiv"><img src="{% static "images/photo5.jpg" %}"  /></div>
			<div class="contentdiv"><img src="{% static "images/photo6.jpg" %}"  /></div>
		</div>
		<div id="paginate-slider1" class="pagination">
		</div>
		<script type="text/javascript">
		featuredcontentslider.init({
			id: "slider1",  //id of main slider DIV
			contentsource: ["inline", ""],  //Valid values: ["inline", ""] or ["ajax", "path_to_file"]
			toc: "#increment",  //Valid values: "#increment", "markup", ["label1", "label2", etc]
			nextprev: ["Previous", "Next"],  //labels for "prev" and "next" links. Set to "" to hide.
			revealtype: "click", //Behavior of pagination links to reveal the slides: "click" or "mouseover"
			enablefade: [true, 0.2],  //[true/false, fadedegree]
			autorotate: [true, 3000],  //[true/false, pausetime]
			onChange: function(previndex, curindex, contentdivs){  //event handler fired whenever script changes slide
				//previndex holds index of last slide viewed b4 current (0=1st slide, 1=2nd etc)
				//curindex holds index of currently shown slide (0=1st slide, 1=2nd etc)
			}
		})
		</script>
	</div>

	<div class="home-right-panel">

		<h2>Our Staff</h2>

		<div id="staff-box-1">

			<div id="p-select" class="glidecontenttoggler">
				GB Consitution
				<a href="#" class="next"><img src="{% static "images/small-arrow2.png" %}"  /></a>
				<img src="{% static "images/pipe.png" %}"  class="pipe" />
				<a href="#" class="prev"><img src="{% static "images/small-arrow1.png" %}"  /></a>
			</div>

			<div id="canadaprovinces" class="glidecontentwrapper">
				{% if gb %}
					{% for each in gb %}
						<div class="glidecontent">
							<img src="{{each.picture.url}}" style="height:125px;" />
							<strong>{{each.name}}</strong>
							{{each.title}}
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
		<br />
		<div id="staff-box-2">

			<div id="p-select2" class="glidecontenttoggler">
				Adminstrative Staff
				<a href="#" class="next"><img src="{% static "images/small-arrow2.png" %}"  /></a>
				<img src="{% static "images/pipe.png" %}"  class="pipe" />
				<a href="#" class="prev"><img src="{% static "images/small-arrow1.png" %}"  /></a>
			</div>
			<div id="canadaprovinces2" class="glidecontentwrapper">
				{% if staff %}
					{% for each in staff %}
						<div class="glidecontent">
							<img src="{{each.picture.url}}" style="height:125px;"  />
							<strong>{{each.name}}</strong>
							{{each.title}}
						</div>
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>

</div>

{% endblock content %}

templates/photologue/includes/gallery_sample.html
{% load i18n %}

{# Display a randomnly-selected set of photos from a given gallery #}

<div class="event-box">
    <a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a>
</div>